### ISSUE TITLE
Missing cell value causes a nullpointer exception. 

### ISSUE THREAD

**Issue by noitcudni** [Cascading/maple#30]
Here's a stack trace.

cascading.tuple.TupleException: unable to read from input identifier: 'unknown'
    at cascading.tuple.TupleEntrySchemeIterator.hasNext(TupleEntrySchemeIterator.java:127)
    at cascading.flow.stream.SourceStage.map(SourceStage.java:76)
    at cascading.flow.stream.SourceStage.run(SourceStage.java:58)
    at cascading.flow.hadoop.FlowMapper.run(FlowMapper.java:124)
    at org.apache.hadoop.mapred.MapTask.runOldMapper(MapTask.java:358)
    at org.apache.hadoop.mapred.MapTask.run(MapTask.java:307)
    at org.apache.hadoop.mapred.LocalJobRunner$Job.run(LocalJobRunner.java:176)
Caused by: java.lang.NullPointerException
    at org.apache.hadoop.hbase.io.ImmutableBytesWritable.<init>(ImmutableBytesWritable.java:60)
    at com.twitter.maple.hbase.HBaseScheme.source(Unknown Source)
    at cascading.tuple.TupleEntrySchemeIterator.getNext(TupleEntrySchemeIterator.java:140)
    at cascading.tuple.TupleEntrySchemeIterator.hasNext(TupleEntrySchemeIterator.java:120)
    ... 6 more

If my table in hbase has a schema that looks like the following.
table_name: test
column_family : cf

Say that my HbaseScheme is expecting value fields: foo and bar and the test table has the following rows.

1, cf:foo="hello", cf:bar="world"
2, cf:foo="bye"

Row 2 will cause the exception described above.

I'd expect that an empty byte array will be returned for row 2's cf:bar column.

**Comment by noitcudni** [comment]
I also have a fix for it. Let me know if this is really an issue.

**Comment by azymnis** [comment]
Yes this is a bug. Please submit a pull request against the develop branch and I will merge it in.

**Comment by noitcudni** [comment]
https://github.com/Cascading/maple/pull/31
